// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.user_id", "0984291b-901e-4654-a900-841eb17b4f76");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1571427005);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1571427125);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1571426525);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1571426765);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1571426645);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1571426885);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1571427365);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1571427245);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 3408);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1571426504);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 86);
user_pref("browser.newtabpage.activity-stream.impressionId", "{f2d333a0-495e-4d7c-85d0-57e55b48a5a6}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1571426525509");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1571428323509");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1571426514523");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1571430114523");
user_pref("browser.search.region", "IN");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1571426507");
user_pref("browser.slowStartup.averageTime", 27367);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20190828152820");
user_pref("browser.startup.homepage_override.mstone", "69.0");
user_pref("browser.startup.lastColdStartupCheck", 1571426506);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1571426510635");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "69.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "a9f178e14a2c444c9291a0f6b7551fe6");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Wed, 16 Oct 2019 14:24:08 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1571427008);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "69.0");
user_pref("extensions.lastPlatformVersion", "69.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{85edcf6a-9224-4f23-9379-d1a284099997}\",\"addons\":{\"doh-rollout@mozilla.org\":{\"version\":\"1.0.0\"},\"webcompat@mozilla.org\":{\"version\":\"6.1.0\"}}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"0d9dd591-be44-43db-967c-85dcd7df9f83\",\"fxmonitor@mozilla.org\":\"eefc8c0b-a1a1-4152-8e32-4726d870dcb8\",\"screenshots@mozilla.org\":\"2ac2d9bf-2313-4397-a9d3-2e696a3f6937\",\"webcompat-reporter@mozilla.org\":\"82bfe790-e026-480a-bae2-d80eb46d06e3\",\"webcompat@mozilla.org\":\"7e3b4f7c-5039-402c-a113-93e45168b996\",\"default-theme@mozilla.org\":\"be3c19b2-584b-4c5f-84b8-9f90550c4e4a\",\"google@search.mozilla.org\":\"622eee9b-542b-41b2-b341-3488dbf32f81\",\"amazondotcom@search.mozilla.org\":\"c4617386-f061-4200-bb02-f1e694b9d55b\",\"bing@search.mozilla.org\":\"aee66311-7b1d-4256-81b5-204f16f449fe\",\"ddg@search.mozilla.org\":\"8daa1198-3626-49a8-aa68-eb44238f20cc\",\"ebay@search.mozilla.org\":\"54d41ad1-0374-4f60-8eb5-c8dd8b2f339b\",\"twitter@search.mozilla.org\":\"b7ade9ae-e161-4811-850e-0b7ecf510d04\",\"wikipedia@search.mozilla.org\":\"457101bd-b39d-475e-9f4d-6be9baad260a\",\"doh-rollout@mozilla.org\":\"4cd998f9-8971-4383-a293-ed0d35dc198f\"}");
user_pref("idle.lastDailyNotification", 1571426868);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1571426714);
user_pref("media.gmp-gmpopenh264.version", "1.8.1");
user_pref("media.gmp-manager.buildID", "20190828152820");
user_pref("media.gmp-manager.lastCheck", 1571426711);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1571426869);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "10b012d0-c219-4c86-a561-c7819ff45915");
user_pref("security.sandbox.plugin.tempDirSuffix", "4a371669-ca76-4534-b7f3-8bccff3fb535");
user_pref("services.blocklist.pinning.checked", 1571426710);
user_pref("services.settings.clock_skew_seconds", -255);
user_pref("services.settings.last_etag", "\"1571421500037\"");
user_pref("services.settings.last_update_seconds", 1571427140);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1571426710);
user_pref("services.settings.main.cfr-fxa.last_check", 1571426710);
user_pref("services.settings.main.cfr.last_check", 1571426710);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1571426710);
user_pref("services.settings.main.hijack-blocklists.last_check", 1571426710);
user_pref("services.settings.main.language-dictionaries.last_check", 1571426710);
user_pref("services.settings.main.normandy-recipes.last_check", 1571426710);
user_pref("services.settings.main.sites-classification.last_check", 1571426710);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1571426710);
user_pref("services.settings.security.onecrl.checked", 1571426710);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1571426868);
user_pref("toolkit.startup.last_success", 1571426478);
user_pref("toolkit.telemetry.cachedClientID", "051d0698-22ad-4f24-8c38-55a93cb86703");
user_pref("toolkit.telemetry.previousBuildID", "20190828152820");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.extendedTriplets.experiment", "control");
